.TH CLIPB "1" "2021" "NNB" "User Commands"
.SH NAME
ClipB \- Clipboard managers warper that SuperB
.SH SYNOPSIS
.B clipb copy TEXTS
.TP
.B clipb paste
.TP
.B clipb help
.SH DESCRIPTION
Terminal explorer is a files manager tool written in pure sh that mimic the way GUI's file manager do copy/cut/paste.
.SH OPTIONS
\fBcopy\fR
copy TEXTS to clipboard
.TP
\fBpaste\fR
paste from clipboard
.TP
\fBhelp\fR
display this help and exit
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/clipb/issues
